### ISSUE TITLE
The service refused the connection - perhaps it is offline

### ISSUE THREAD

**Issue by vmwinckler** [felipefontoura/doc2md#9]
![Image](https://github.com/user-attachments/assets/f80936d0-095c-4c1b-90dd-8e1a896b3c41)

![Image](https://github.com/user-attachments/assets/3a0dc60c-fd7c-4c92-8df6-9c265425a35d)

{ "headers": { "content-length": 1302782, "content-type": "application/pdf", "accept": "application/json,text/html,application/xhtml+xml,application/xml,text/*;q=0.9, image/*;q=0.8, */*;q=0.7" }, "method": "POST", "uri": "http://doc2md.wincktech.com.br:5000/convert", "gzip": true, "rejectUnauthorized": true, "followRedirect": true, "resolveWithFullResponse": true, "followAllRedirects": true, "timeout": 300000, "body": "Binary data got replaced with this text. Original was a Buffer with a size of 1302782 bytes.", "encoding": null, "json": false, "useStream": true }

**Comment by vmwinckler** [comment]
Utilizei o docker compose da data de ontem para gerar a stack no meu portainer

**Comment by ilsondev** [comment]
Eu estava tendo esse erro, só resolveu quando eu adicionei as variáveis de ambiente da OpenAI que está no env.example do repositório.

**Comment by ilsondev** [comment]
```
services:
  doc2md:
    image: 'felipefontoura/doc2md:latest'
    environment:
      - 'OPENAI_API_KEY=${OPENAI_API_KEY}'
      - 'LLM_MODEL=${LLM_MODEL}'
      - 'WORKERS=${WORKERS}'
      - 'TIMEOUT=${TIMEOUT}'
    ports:
      - "5000:5000"
    volumes:
      - 'doc2md:/home/node/doc2md'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  doc2md:
    external: false
```

Utilizei esse docker compose para rodar no meu Coolify e cadastrei minhas variáveis de ambiente dentro do painel do Coolify. Rodou perfeitamente.
